In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]

In [3]:
my_list

[1, 2, 3, 4, 5]

In [4]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Numpy arange

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

# Numpy Zeros and Ones 

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Linespace 
evenly seperated example np.linespace(0,10,3) means 3 numbers between 0 and 10 evenly seperated

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,12,6)

array([ 0. ,  2.4,  4.8,  7.2,  9.6, 12. ])

In [21]:
np.linspace(1,12,12)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

# eye
creates identity matrix

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random
rand

In [23]:
np.random.rand(5)

array([0.92463951, 0.95253435, 0.16652883, 0.95844517, 0.42956874])

randn

In [24]:
np.random.randn(5)

array([-0.69173453, -0.63279838, -0.10281746,  1.08611002,  1.08371842])

randint
Lower range is included and higher is excluded with numer of random integers you want

In [31]:
np.random.randint(5,10,5)

array([8, 6, 7, 7, 8])